### ISSUE TITLE
Unused os.path.join in chat_photo.py

### ISSUE THREAD

**Issue by andreymal** [aiogram/aiogram#740]
I was looking at the aiogram code on github accidentally found that `os.path.join` is not used here, which is suspicious.

https://github.com/aiogram/aiogram/blob/df294e579f104e2ae7e9f37b0c69490782d33091/aiogram/types/chat_photo.py#L62-L63

**Comment by JrooTJunior** [comment]
Fixed in latest release

**Comment by andreymal** [comment]
Um, I still see it in the latest commit https://github.com/aiogram/aiogram/tree/bccfca7c/aiogram/types/chat_photo.py#L36

**Comment by andreymal** [comment]
@JrooTJunior what's happening with these lines? They are still not fixed

**Comment by Olegt0rr** [comment]
I can't find the fix too. 

```python
destination = os.path.join(destination, file.file_path)
```

**Comment by JrooTJunior** [comment]
Oh crap..
Thx, I should re-check this functionality.
